export const contentSavedLinksLocal = {
  id: {
    pageTitle: "Saved Links",
    heroTitle: "Bangun knowledge vault Anda sendiri.",
    heroDesc: "Simpan artikel, video, referensi, dan temuan berguna dalam satu perpustakaan yang terorganisir dan mudah diakses.",
    heroTag: "Saved Links",
    addNewLink: "Tambah link baru",
    totalLinks: "Total link",
    totalLinksDesc: "Referensi tersimpan di vault Anda",
    labelsUsed: "Label dipakai",
    labelsUsedDesc: "Topik dan kategori terorganisir",
    recentSaves: "Simpanan terbaru",
    recentSavesDesc: "Koleksi yang dimuat di halaman ini",
    topSource: "Sumber teratas",
    topSourceDesc: "link tersimpan",
    noTopSource: "Belum ada wawasan domain",
    searchPlaceholder: "Cari judul, url, atau label...",
    filterAll: "Semua",
    filterLabeled: "Berlabel",
    filterUnlabeled: "Tanpa Label",
    filterRecent: "Terbaru",
    topLabels: "Label teratas",
    topLabelsDesc: "Jaga vault tetap rapi dengan label yang paling sering dipakai.",
    noLabels: "Belum ada label.",
    allSavedLinks: "Semua link tersimpan",
    allSavedLinksDesc: "Jelajahi koleksi lengkap dalam tata letak yang lebih bersih dan teratur.",
    noResults: "Tidak ada link yang cocok dengan pencarian atau filter saat ini.",
    seeMore: "Lihat lebih banyak",
    noLabel: "—",
    noLabelList: "Tanpa label",
    loginRequired: "Login dulu untuk melihat koleksi link tersimpan Anda.",
    login: "Login",
    copied: "Tersalin",
  },
  en: {
    pageTitle: "Saved Links",
    heroTitle: "Build your own knowledge vault.",
    heroDesc: "Save articles, videos, references, and useful finds in one organized library that is easy to scan and reuse.",
    heroTag: "Saved Links",
    addNewLink: "Add new link",
    totalLinks: "Total links",
    totalLinksDesc: "Your saved references across the vault",
    labelsUsed: "Labels used",
    labelsUsedDesc: "Organized topics and categories",
    recentSaves: "Recent saves",
    recentSavesDesc: "Current collection loaded in this page",
    topSource: "Top source",
    topSourceDesc: "saved link(s)",
    noTopSource: "No domain insight yet",
    searchPlaceholder: "Search title, url, or label...",
    filterAll: "All",
    filterLabeled: "Labeled",
    filterUnlabeled: "Unlabeled",
    filterRecent: "Recent",
    topLabels: "Top labels",
    topLabelsDesc: "Keep your vault organized with the labels you use most.",
    noLabels: "No labels yet.",
    allSavedLinks: "All saved links",
    allSavedLinksDesc: "Browse your full collection in a cleaner, more organized layout.",
    noResults: "No links match your current search or filter.",
    seeMore: "See more",
    noLabel: "—",
    noLabelList: "No label",
    loginRequired: "Login to view your saved links collection.",
    login: "Login",
    copied: "Copied",
  },
};