
export const contentMoneyLocal = {
  id: {
    title: "Money Tracker",
    subtitle: "Keuangan",
    desc: "Transaksi, anggaran, goals, multi akun, ekspor/impor, dan wawasan bulanan.",
    monthLabel: "Bulan",
    refresh: "Segarkan",
    exportCsv: "Ekspor CSV",
    importCsv: "Impor CSV",
    balance: "Saldo",
    income: "Pemasukan",
    expense: "Pengeluaran",
    topSpending: "Pengeluaran Tertinggi",
    alerts: "Peringatan",
    cashflowOverview: "Ikhtisar Arus Kas",
    cashflowDesc: "Pantau momentum pengeluaran Anda selama 6 bulan terakhir.",
    highestExpense: "Pengeluaran Tertinggi",
    highestIncome: "Pemasukan Tertinggi",
    highestExpenseDesc: "Berdasarkan sub kategori bulan ini",
    highestIncomeDesc: "Berdasarkan sub kategori bulan ini",
    categoryAlloc: "Alokasi Kategori",
    categoryAllocDesc: "Distribusi pengeluaran kategori induk",
    categoryAllocDescInc: "Distribusi pemasukan kategori induk",
    compareMonthly: "Komparasi Bulanan",
    compareMonthlyDesc: "Bulan ini vs bulan lalu (Sub Kategori)",
    subCategory: "Sub Kategori",
    parentCategory: "Induk Kategori",
    total: "Total",
    thisMonth: "Ini",
    lastMonth: "Lalu",
    noExpense: "Belum ada pengeluaran",
    noIncome: "Belum ada pemasukan",
    noData: "Belum ada data",
    newItem: "Baru",
    otherItem: "Lain-lain",
    addTx: "Tambah Transaksi",
    transfer: "Transfer",
    newGoal: "Goal Baru",
    accountOverview: "Ikhtisar Akun",
    accountDesc: "Pengaturan akun Anda untuk pengeluaran dan transfer.",
    noAccounts: "Belum ada akun. Tambahkan akun pertama Anda untuk mulai melacak saldo.",
    budgetHealth: "Kesehatan Anggaran",
    budgetDesc: "Lihat kategori mana yang aman, mendekati, atau melebihi anggaran.",
    noBudgets: "Belum ada anggaran untuk bulan ini.",
    recentTxs: "Transaksi Terakhir",
    recentDesc: "Pindai cepat pergerakan uang terbaru bulan ini.",
    viewAll: "Lihat Semua",
    noTxs: "Belum ada transaksi bulan ini.",
    monthlyInsight: "Wawasan Bulanan",
    insightDesc: "Ringkasan sederhana ke mana uang Anda pergi.",
    highestSpendingLabel: "Kategori pengeluaran tertinggi bulan ini.",
    loadingInsight: "Memuat wawasan...",
    categoryDist: "Distribusi Kategori",
    categoryDistDesc: "Lihat apa yang mendominasi pengeluaran Anda.",
    goalsSnapshot: "Ringkasan Goals",
    goalsSnapshotDesc: "Pantau target tabungan sambil mengelola arus kas.",
    openGoals: "Buka Goals",
    noGoals: "Belum ada goals. Buat satu untuk melacak progres tabungan.",
    tabDashboard: "Dashboard",
    tabTransactions: "Transaksi",
    tabCategories: "Kategori",
    tabBudgets: "Anggaran",
    tabAccounts: "Akun",
    tabAnalytics: "Analitik",
    tabGoals: "Goals",
    addCategory: "Kategori Baru",
    addAccount: "Akun Baru",
    setBudget: "Set Anggaran",
    dashboard: "Dashboard",
    transactions: "Transaksi",
    categories: "Kategori",
    budgets: "Anggaran",
    accounts: "Akun",
    analytics: "Analitik",
    goals: "Goals",
    loginRequired: "Login dulu untuk memakai fitur money tracker.",
    errorLoadCore: "Gagal memuat data money tracker",
    errorLoadMonth: "Gagal memuat data bulanan",
    saved: "Tersimpan",
    target: "Target",
    left: "Sisa",
    progress: "Progres",
    noDeadline: "Tidak ada tenggat waktu",
    targetDate: "Tanggal target",
    activeGoals: "goals aktif",
    aim: "Sasaran",
    now: "Sekarang",
    rate: "Rasio",
    closestToFinish: "Terdekat selesai",
    mostRemaining: "Paling banyak sisa",
    quickActions: "Aksi cepat",
    createGoal: "Buat goal",
    backToDashboard: "Kembali ke dashboard",
    editTx: "Edit Transaksi",
    txType: "Tipe",
    txAccount: "Akun",
    txCategory: "Kategori",
    txDate: "Tanggal",
    txAmount: "Jumlah",
    txCurrency: "Mata Uang",
    txTags: "Label",
    txNote: "Catatan",
    cancel: "Batal",
    save: "Simpan",
    txDesc: "Pemasukan atau pengeluaran dengan kategori dan label.",
    transferDesc: "Pindahkan saldo antar akun (mata uang harus sama).",
    from: "Dari",
    to: "Ke",
    categoryKind: "Jenis",
    categoryName: "Nama",
    categoryDesc: "Buat kategori untuk pemasukan atau pengeluaran.",
    accountType: "Tipe",
    initialBalance: "Saldo Awal",
    accountDescLong: "Buat akun baru untuk melacak uang tunai/bank/e-wallet.",
    budgetLimit: "Batas",
    budgetDescLong: "Anggaran per kategori pengeluaran.",
    goalDescLong: "Buat target tabungan baru dengan nominal dan tenggat waktu.",
    livePreview: "Pratinjau",
    goalProgressBoard: "Papan Progres Goal",
    goalBoardDesc: "Lihat target, progres, dan tenggat waktu dalam satu tempat yang lebih mudah dipantau.",
    goalInsights: "Wawasan Goal",
    goalInsightsDesc: "Ringkasan cepat untuk melihat kesehatan target tabungan Anda.",
    noGoalInsights: "Belum ada wawasan goal.",
    addContribution: "Isi Tabungan",
    deleteGoal: "Hapus Target",
    startFirstGoal: "Mulai target pertamamu 🚀",
    firstGoalDesc: "Capai impianmu (Motor, Rumah, Liburan) dengan mulus dan terencana.",
    createGoalNow: "Buat Target Sekarang",
    remainingDays: "Tersisa",
    days: "Hari",
    savePerMonth: "Tabung per bulan",
    insightNoDeadline: "Lanjutkan tabunganmu! Belum ada deadline target.",
    insightAhead: "Kamu lebih cepat dari jadwal! Pertahankan.",
    insightOnTrack: "Kamu tepat berada di jalur target!",
    insightBehind: "Progres tertinggal. Tambah tabunganmu.",
    insightDone: "Luar biasa! Target sudah tercapai.",
    insightNotStarted: "Waktu tabungan belum dimulai.",
    insightBehindAmount: (amount: string) => `Tertinggal sekitar ${amount} dari target saat ini.`,
    insightOnTrackNoDate: "On track, lanjutkan!",
    quickActionsGoalDesc: "Tambah target baru atau lanjut atur strategi tabungan.",
    txDescLong: "Pemasukan atau pengeluaran dengan kategori dan label.",
    txAmountPlaceholder: "100000",
    selectType: "Pilih tipe",
    selectAccount: "Pilih akun",
    optional: "Opsional",
    tagsPlaceholder: "contoh: belanja, keluarga",
    transferDescLong: "Pindahkan saldo antar akun (misal: Bank ke Tunai).",
    categoryDescLong: "Buat kategori untuk pemasukan atau pengeluaran.",
    kind: "Jenis",
    selectKind: "Pilih jenis",
    create: "Buat",
    close: "Tutup",
    amount: "Jumlah",
    date: "Tanggal",
    note: "Catatan",
    accountName: "Nama Akun",
    goalName: "Nama Goal",
    saved_short: "Tersimpan",
    targetAmount: "Target jumlah",
    currentAmount: "Jumlah saat ini",
  },
  en: {
    title: "Money Tracker",
    subtitle: "Finance",
    desc: "Transactions, budget, goals, multi account, export/import, and monthly insights.",
    monthLabel: "Month",
    refresh: "Refresh",
    exportCsv: "Export CSV",
    importCsv: "Import CSV",
    balance: "Balance",
    income: "Income",
    expense: "Expense",
    alerts: "Alerts",
    cashflowOverview: "Cashflow overview",
    cashflowDesc: "Track the momentum of your expenses over the last 6 months.",
    highestExpense: "Highest Expenses",
    highestIncome: "Top Incomes",
    highestExpenseDesc: "Based on subcategories this month",
    highestIncomeDesc: "Based on subcategories this month",
    categoryAlloc: "Category Allocation",
    categoryAllocDesc: "Distribution of parent expense categories",
    categoryAllocDescInc: "Distribution of parent income categories",
    compareMonthly: "Monthly Comparison",
    compareMonthlyDesc: "This month vs last month (Sub Categories)",
    subCategory: "Sub Category",
    parentCategory: "Parent Category",
    total: "Total",
    thisMonth: "This",
    lastMonth: "Last",
    noExpense: "No expenses yet",
    noIncome: "No incomes yet",
    noData: "No data available",
    newItem: "New",
    otherItem: "Other",
    addTx: "Add transaction",
    transfer: "Transfer",
    newGoal: "New goal",
    accountOverview: "Account overview",
    accountDesc: "Your available account setup for spending and transfers.",
    noAccounts: "No accounts yet. Add your first account to start tracking balance.",
    budgetHealth: "Budget health",
    budgetDesc: "See which categories are safe, close, or over budget.",
    noBudgets: "No budgets set for this month.",
    recentTxs: "Recent transactions",
    topSpending: "Top Spending",
    recentDesc: "A quick scan of the latest money movement this month.",
    viewAll: "View all",
    noTxs: "No transactions yet for this month.",
    monthlyInsight: "Monthly insight",
    insightDesc: "Simple read on where your money is going.",
    highestSpendingLabel: "Highest spending category for this month.",
    loadingInsight: "Loading insight...",
    categoryDist: "Category distribution",
    categoryDistDesc: "See what dominates your expenses.",
    goalsSnapshot: "Goals snapshot",
    goalsSnapshotDesc: "Keep savings targets visible while managing cashflow.",
    openGoals: "Open goals",
    noGoals: "No goals yet. Create one to track saving progress.",
    tabDashboard: "Dashboard",
    tabTransactions: "Transactions",
    tabCategories: "Categories",
    tabBudgets: "Budgets",
    tabAccounts: "Accounts",
    tabAnalytics: "Analytics",
    tabGoals: "Goals",
    addCategory: "New Category",
    addAccount: "New Account",
    setBudget: "Set Budget",
    dashboard: "Dashboard",
    transactions: "Transactions",
    categories: "Categories",
    budgets: "Budgets",
    accounts: "Accounts",
    analytics: "Analytics",
    goals: "Goals",
    loginRequired: "Login first to use the money tracker feature.",
    errorLoadCore: "Failed to load money tracker data",
    errorLoadMonth: "Failed to load monthly data",
    saved: "Saved",
    target: "Target",
    left: "Left",
    progress: "Progress",
    noDeadline: "No deadline set",
    targetDate: "Target date",
    activeGoals: "active goals",
    aim: "Aim",
    now: "Now",
    rate: "Rate",
    closestToFinish: "Closest to finish",
    mostRemaining: "Most remaining",
    quickActions: "Quick actions",
    createGoal: "Create goal",
    backToDashboard: "Back to dashboard",
    editTx: "Edit Transaction",
    txType: "Type",
    txAccount: "Account",
    txCategory: "Category",
    txDate: "Date",
    txAmount: "Amount",
    txCurrency: "Currency",
    txTags: "Tags",
    txNote: "Note",
    cancel: "Cancel",
    save: "Save",
    txDesc: "Income or expense with category and tags.",
    transferDesc: "Move balance between accounts (same currency required).",
    from: "From",
    to: "To",
    categoryKind: "Kind",
    categoryName: "Name",
    categoryDesc: "Create category for income or expense.",
    accountType: "Type",
    initialBalance: "Initial Balance",
    accountDescLong: "Create new account to track cash/bank/e-wallet.",
    budgetLimit: "Limit",
    budgetDescLong: "Budget per expense category.",
    goalDescLong: "Create new savings goal with target and deadline.",
    livePreview: "Live preview",
    goalProgressBoard: "Goal Progress Board",
    goalBoardDesc: "See your targets, progress, and deadlines in one easy-to-monitor place.",
    goalInsights: "Goal Insights",
    goalInsightsDesc: "A quick snapshot to read the health of your savings targets.",
    noGoalInsights: "No goal insights yet.",
    addContribution: "Add Contribution",
    deleteGoal: "Delete Goal",
    startFirstGoal: "Start your first goal 🚀",
    firstGoalDesc: "Achieve your dreams (Bike, House, Vacation) smoothly and with a plan.",
    createGoalNow: "Create Goal Now",
    remainingDays: "Remaining",
    days: "Days",
    savePerMonth: "Save per month",
    insightNoDeadline: "Keep saving! There's no target deadline yet.",
    insightAhead: "You are ahead of schedule! Keep it up.",
    insightOnTrack: "You are right on track!",
    insightBehind: "Progress is behind schedule. Boost your savings.",
    insightDone: "Awesome! Your target is already reached.",
    insightNotStarted: "The saving period hasn't started yet.",
    insightBehindAmount: (amount: string) => `Behind by around ${amount} from current target.`,
    insightOnTrackNoDate: "On track, keep going!",
    quickActionsGoalDesc: "Add a new target or continue planning your savings strategy.",
    txDescLong: "Income or expense with categories and tags.",
    txAmountPlaceholder: "100000",
    selectType: "Select type",
    selectAccount: "Select account",
    optional: "Optional",
    tagsPlaceholder: "e.g., groceries, family",
    transferDescLong: "Move balance between accounts (e.g., Bank to Cash).",
    categoryDescLong: "Create a category for income or expenses.",
    kind: "Jenis",
    selectKind: "Select kind",
    create: "Create",
    close: "Close",
    amount: "Amount",
    date: "Date",
    note: "Note",
    accountName: "Account Name",
    goalName: "Goal Name",
    saved_short: "Saved",
    targetAmount: "Target amount",
    currentAmount: "Current amount",
  },
};
